# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Raspberry camera rtsp server add-on
version: "0.0.1a"
slug: rpi-camera-rtsp-server
description: RTSP stream from raspberry camera
url: "https://github.com/lpt2007/hassos-addons-testing/tree/main/rpi-camera-rtsp-server"
arch:
  - armhf
  - armv7
init: false
ports:
  8554/tcp: null
ports_description:
  8554/tcp: Web interface (Not required for Ingress)
video: true
schema:
  message: "str?"
image: "itsiotdevice/rpi-camera-rtsp-server"
