name: nginx
version: "1.0.2a"
slug: nginx
description: Nginx Addon
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: application
boot: manual
options:
  ssl:
    type: boolean
    description: Enable SSL support
    default: false
  certfile:
    type: string
    description: Path to SSL certificate file
    default: ""
  keyfile:
    type: string
    description: Path to SSL key file
    default: ""
  port:
    type: int
    description: Port to serve HTTP traffic on
    default: 80
ports:
  - 80:80/tcp
