arch:
  - amd64

description: "Home Assistant addon with web server and PHP 8 for InvoicePlane"
slug: "invoiceplane-addon"
version: "0.0.002a"

log_level: info
docker_image: https://github.com/lpt2007/hassos-addons-testing/tree/main/invoiceplane
name: InvoicePlane
