description: "Home Assistant addon with web server and PHP 8 for InvoicePlane"
slug: "invoiceplane-addon"
version: "0.0.064a"
arch:
  - amd64
init: false

options:
  document_root: /share/invoiceplane
#  php_ini: default
#  default_conf: default
#  default_ssl_conf: default
#  website_name: null
#  ssl: true
#  certfile: fullchain.pem
#  keyfile: privkey.pem
#  init_commands: []
schema:
  document_root: str
#  php_ini: str
#  default_conf: str
#  default_ssl_conf: str
#  website_name: str
#  username: str?
#  password: password?
#  ssl: bool
#  certfile: str
#  keyfile: str
#  init_commands:
#    - str?

ports:
  8080/tcp: 81
  443/tcp: 444
ports_description:
  8080/tcp: Web interface http
  443/tcp: SSL Web interface

log_level: info
  
docker_image: https://github.com/lpt2007/hassos-addons-testing/tree/main/invoiceplane
name: InvoicePlane
map:
 - share:rw

