name: nginx
version: "1.0.2a"
slug: nginx
description: Nginx Addon
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: application
boot: manual
options:
  ssl: false
  certfile: ""
  keyfile: ""
ports:
  - 80:80/tcp
