name: nginx
version: "1.0.3a"
slug: nginx
description: Nginx Addon
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: application
boot: manual
options:
  ssl:
    required: false
    default: false
    description: Use SSL
    example: true
  certfile:
    required: false
    default: ""
    description: SSL certificate file path
    example: /ssl/cert.pem
  keyfile:
    required: false
    default: ""
    description: SSL key file path
    example: /ssl/key.pem
  port:
    required: false
    default: 80
    description: Port to use for HTTP requests
    example: 8080
