description: "Home Assistant addon with web server and PHP 8 for InvoicePlane"
slug: "invoiceplane-addon"
version: "0.0.027a"
arch:
  - amd64
init: false

ports:
  80/tcp: 81
  443/tcp: 444
ports_description:
  80/tcp: Web interface http
  443/tcp: SSL Web interface

log_level: info
docker_image: https://github.com/lpt2007/hassos-addons-testing/tree/main/invoiceplane
name: InvoicePlane

