name: nginx
version: "1.0.1a"
slug: nginx
description: Nginx Addon
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: application
boot: manual
options:
  ssl: false
  certfile: ""
  keyfile: ""
  port: 80
