description: "Home Assistant addon with web server and PHP 8 for InvoicePlane"
slug: "invoiceplane-addon"
version: "0.0.057a"
arch:
  - amd64
init: false

ports:
  8080/tcp: 81
  443/tcp: 444
ports_description:
  8080/tcp: Web interface http
  443/tcp: SSL Web interface

log_level: info

options:
  data_path:
    name: "data_path"
    description: "Path to InvoicePlane installation directory"
    type: "str"
    default: "/share/www/invoiceplane"
    schema:
      type: "string"
      minLength: 1
      format: "directory"

docker_image: https://github.com/lpt2007/hassos-addons-testing/tree/main/invoiceplane
name: InvoicePlane
map:
 - share:rw

