# Home Assistant Add-on for InvoicePlane

# Add-on slug (lowercase)
slug: invoiceplane

# Add-on name and description
name: InvoicePlane
description: Run InvoicePlane web app in a Docker container

# Docker image
#image: mhzawadi/invoiceplane:latest

# Customize ports
ports:
  80/tcp: 80

# Home Assistant API token (optional)
# Uncomment the following line to enable
# ha_access_token: YOUR_HOME_ASSISTANT_API_TOKEN

# Map data directory
data:
  - name: invoiceplane-data
    path: /data

# Map log directory
log:
  - name: invoiceplane-log
    path: /logs
