# config.yaml

slug: kodi-gui
name: Kodi GUI
version: 1.0.04a
description: A Home Assistant addon to run Kodi media player in GUI mode.
# Define the URL of the add-on repository
url: https://github.com/lpt2007/hassos-addons-testing
# Define the author of the add-on
author: ELITS
arch:
  - aarch64
  - amd64
  - armv7
repository: https://github.com/example/kodi-gui-addon
dockerhub: example/kodi-gui-addon
homeassistant:
  # The latest version of Home Assistant
  version: "2022.2.2"
  # The version of the Supervisor
  supervisor: "2022.02.0"
  # The list of required services
  services:
    - kodi
  # The list of supported architectures
  target:
    - aarch64
    - amd64
    - armv7
# omogoči popoln dostop do hardware opreme
full_access: true
# omogoči dostop do grafike in zvoka
audio: true
video: true
# Define the devices required by the add-on
devices:
  - /dev/dri
  - /dev/fb0
  - /dev/snd
# Define the environment variables for the add-on
env_vars:
  DISPLAY: ":0"
options:
  audio_output: ALSA
  video_output: EGL
config:
  # Home Assistant integration
  mqtt: true

  # Kodi settings
  enable-webserver: true
  http-port: 8080
  allow-remote-control: true
  zeroconf: true

log_level: info
