name: Kodi Media Player
version: 1.0.0a
slug: kodi-media-player
description: Kodi Media Player add-on for Home Assistant
url: https://github.com/USERNAME/kodi-media-player-addon
documentation: https://github.com/USERNAME/kodi-media-player-addon/blob/main/README.md
arch:
  - amd64
  - armv7
  - aarch64

docker:
  image: linuxserver/kodi
  network_mode: host

hosts:
  - core-ssh

ports:
  8080/tcp:
    name: Kodi HTTP
    description: Kodi HTTP port

options:
  audio_output: ALSA
  video_output: EGL

config:
  # Home Assistant integration
  mqtt: true

  # Kodi settings
  enable-webserver: true
  http-port: 8080
  allow-remote-control: true
  zeroconf: true

log_level: info
