# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Kodi with samba share add-on on buster
version: "0.0.1a"
slug: kodi-smb_buster
description: Kodi with samba share add-on on buster
url: "https://github.com/lpt2007/hassos-addons-testing/tree/main/kodi-smb_buster"
arch:
  - armhf
  - armv7
host_dbus: true
devices:
  - /dev/input/event0
#full_access: true
audio: true
video: true
usb: true
init: false
options:
  message: "Hello to Kodi with samba..."
schema:
  message: "str?"
