# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Raspberry camera rtsp add-on
version: "0.0.1"
slug: rpi-camera-rtsp

description: Raspberry camera rtsp add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
init: false
options:
  message: "aspberry camera rtsp add-on"
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
