#!/bin/sh
#DocumentRoot=$(bashio::config 'document_root')

# Preveri, ali je mapa /share/invoiceplane že nameščena
if [ -d "/share/invoiceplane" ]; then
  echo "InvoicePlane je že nameščen."
  ln -s /share/invoiceplane/ip/* /var/www/html/
  echo "Mapa uspešno povezana na strežnik"
  exit 1
fi

# Preveri, ali je dosegljiva povezava do GitHuba
if ! curl --output /dev/null --silent --head --fail "https://github.com/InvoicePlane/InvoicePlane/releases/download/v1.6.1-beta-2/v1.6.1-beta-2.zip"; then
  echo "Ni mogoče prenesti InvoicePlane. Povezava do GitHuba ni na voljo."
  exit 1
fi

# Ustvari mapo, če ta ne obstaja
mkdir -p /share/invoiceplane

# Prenesi InvoicePlane
curl -LJO https://github.com/InvoicePlane/InvoicePlane/releases/download/v1.6.1-beta-2/v1.6.1-beta-2.zip

# Razpakiraj arhiv v mapo /share/invoiceplane
unzip v1.6.1-beta-2.zip -d /share/invoiceplane

# Odstrani preneseni arhiv
rm -f v1.6.1-beta-2.zip

# Sporoči, da je bila namestitev InvoicePlane uspešna
echo "InvoicePlane je bil uspešno nameščen v $document_root."
