---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bullseye
  amd64: ghcr.io/home-assistant/amd64-base-debian:bullseye
  armhf: ghcr.io/home-assistant/armhf-base-raspbian:bullseye
  armv7: ghcr.io/home-assistant/armhf-base-raspbian:bullseye
  i386: ghcr.io/home-assistant/i386-base-debian:bullseye
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
