---
stage: experimental
version: 0.0.002a
full_access: true
hassio_api: true
slug: kodi-base-debian
name: KODI with AV on DEBIAN LINUX
description: KODI with AUDIO and HARDWARE VIDEO ACCELERATION
url: https://github.com/lpt2007/hassos-addons-testing/tree/main/kodi-base-debian
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
audio: true
video: true
devices:
  - /dev/fb0
map:
  - ssl
  - share:rw
