ARG BUILD_FROM
FROM $BUILD_FROM

# Base Dependencies
#RUN apk update && \
#    apk add --no-cache alpine-sdk cmake g++ make nano
    
# Essential Dependencies
#RUN apk update && \
#    apk add --no-cache mesa-dev libva-dev libxslt-dev libjpeg-turbo-dev
    
# Install X11 Libraries and Packages
#RUN apk update && \
#    apk add --no-cache xorg-server xf86-video-dummy
    
# install kodi
#RUN apk add --no-cache kodi

# Copy data
#COPY rootfs /

# default folder
WORKDIR /

#ENV DISPLAY=:0
