# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Kodi with samba share add-on
version: "0.0.1a"
slug: kodi-smb
description: Kodi with samba share add-on
url: "https://github.com/lpt2007/hassos-addons-testing/tree/main/kodi-smb"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  message: "Hello to Kodi with samba..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-base-raspbian"
