---
stage: experimental
version: 0.0.029a
hassio_api: true
slug: nginx_n_php
name: NGINX with PHP
description: NIGINX Server with PHP Support
url: https://github.com/lpt2007/hassos-addons-testing/tree/main/nginx_n_php
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
#image: homeassistant/{arch}-addon-nginx_proxy
init: false
map:
  - ssl
  - share:rw
options:
  domain: null
  hsts: max-age=31536000; includeSubDomains
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: true
  cloudflare: false
  customize:
    active: false
    default: nginx_n_php_default*.conf
    servers: nginx_n_php/*.conf
ports:
  443/tcp: 443
  80/tcp: null
schema:
  domain: str
  hsts: str
  certfile: str
  keyfile: str
  ssl: bool
  cloudflare: bool
  customize:
    active: bool
    default: str
    servers: str
